CREATE TABLE task_executions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_task_id        UUID NOT NULL REFERENCES work_tasks(id),
    action              VARCHAR(32) NOT NULL,
    previous_status     VARCHAR(32),
    status              VARCHAR(32) NOT NULL,
    notes               TEXT,
    executed_by         VARCHAR(255) NOT NULL,
    executed_at         TIMESTAMP NOT NULL,
    task_version        BIGINT NOT NULL
);

CREATE UNIQUE INDEX uk_task_executions_task_version_action
    ON task_executions (work_task_id, task_version, action);

CREATE INDEX idx_task_executions_task_time
    ON task_executions (work_task_id, executed_at DESC, id DESC);

INSERT INTO task_executions (
    work_task_id,
    action,
    previous_status,
    status,
    notes,
    executed_by,
    executed_at,
    task_version
)
SELECT
    id,
    'STARTED',
    NULL,
    'IN_PROGRESS',
    NULL,
    'legacy-migration',
    actual_start,
    CASE
        WHEN status IN ('COMPLETED', 'CANCELLED') AND version > 0 THEN version - 1
        ELSE version
    END
FROM work_tasks
WHERE actual_start IS NOT NULL;

INSERT INTO task_executions (
    work_task_id,
    action,
    previous_status,
    status,
    notes,
    executed_by,
    executed_at,
    task_version
)
SELECT
    id,
    status,
    NULL,
    status,
    notes,
    'legacy-migration',
    updated_at,
    version
FROM work_tasks
WHERE status IN ('COMPLETED', 'CANCELLED');
