listener 1883
allow_anonymous false
password_file /tmp/agricore-mqtt-passwords
acl_file /tmp/agricore-mqtt-acl
persistence true
persistence_location /mosquitto/data/
max_inflight_messages 20
max_packet_size 16384
